project:
  type: website
  output-dir: _site

website:
  title: "Meu Portfólio"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: projetos.qmd
        text: Projetos
    right:
      - icon: github
        href: "https://www.linkedin.com/in/eduardo-oliveira-pereira/"
      - icon: linkedin
        href: "https://www.linkedin.com/in/eduardo-oliveira-pereira/"

format:
  html:
    theme: cosmo
    css: styles.css



